jumps:
  - "0,0,3"
  - "4,-1,4"
  - "-3,0,4"
  - "0,-1,-5"
  - "0,0,2"
  - "0,1,-4"
  - "2,0,3"
  - "0,1,-2"
  - "-1,1,-4"
  - "0,0,4"
  - "0,2,1/0,1,1/0,0,1/0,0,2"
  - "-4,1,-1"
  - "4,0,-1"
  - "-4,0,0"
#### MAKE SURE THAT THE TARGET BLOCK (THE BLOCK THEY LAND ON) IS THE LAST ONE IN THE STRING

blocks:
  - "WOOL:0"
  - "BOOKSHELF:10"
  - "COAL_BLOCK:25"
  - "BEACON:50"
  - "EMERALD_BLOCK:100"
  - "QUARTZ_BLOCK:200"
  - "SPONGE:300"
  - "HAY_BLOCK:400"
  - "MELON:500"
  - "TNT:1000"
  - "RAINBOW:1500"

start-location:
  world: "world"
  coords: "255,84,208"