jumps:
  - "ICE:0,0,3"
  - "BLOCK:4,-1,4"
  - "BLOCK:-3,0,4"
  - "BLOCK:0,-1,-5"
  - "FENCE:0,0,2"
  - "BLOCK:0,1,-4"
  - "BLOCK:2,0,3"
  - "BLOCK:0,1,-2"
  - "BLOCK:-1,1,-4"
  - "ICE:0,0,4"
  - "BLOCK:0,2,1/BLOCK:0,1,1/BLOCK:0,0,1/BLOCK:0,0,2"
  - "BLOCK:-4,1,-1"
  - "BLOCK:4,0,-1"
  - "BLOCK:-4,0,0"
#### MAKE SURE THAT THE TARGET BLOCK (THE BLOCK THEY LAND ON) IS THE LAST ONE IN THE STRING

blocks:
  - "WOOL:0"
  - "BOOKSHELF:10"
  - "COAL_BLOCK:25"
  - "BEACON:50"
  - "EMERALD_BLOCK:100"
  - "QUARTZ_BLOCK:200"
  - "SPONGE:300"
  - "HAY_BLOCK:400"
  - "MELON:500"
  - "TNT:1000"
  - "RAINBOW:1500"

start-location:
  world: "world"
  coords: "255,84,208"