jumps:
  - "0,0,3"
  - "4,-1,4"
  - "-3,0,4"
  - "0,-1,-5"
  - "0,0,2"
  - "0,1,-4"
  - "2:0:3"
  - "0:1:-2"
  - "-1,+1,-4"
  - "0,0,4"
  - "0,2,1/0,1,1/0,0,1/0,0,2"
  - "-4,1,-1"
  - "4,0,-1"
  - "-4,0,0"
#### MAKE SURE THAT THE TARGET BLOCK (THE BLOCK THEY LAND ON) IS THE LAST ONE IN THE STRING

start-location:
  world: "world"
  coords: "255,84,208"