jumps:
  - "ICE:0,0,3"
  - "BLOCK:4,-1,4"
  - "BLOCK:-3,0,4"
  - "BLOCK:0,-1,-5"
  - "FENCE:0,0,2"
  - "BLOCK:0,1,-4"
  - "BLOCK:2,0,3"
  - "BLOCK:0,1,-2"
  - "BLOCK:-1,1,-4"
  - "BLOCK:0,3,4/ICE:0,0,4"
  - "BLOCK:0,2,1/BLOCK:0,1,1/BLOCK:0,0,1/BLOCK:0,0,2"
  - "BLOCK:-4,1,-1"
  - "BLOCK:4,0,-1"
  - "BLOCK:-4,0,0"
#### MAKE SURE THAT THE TARGET BLOCK (THE BLOCK THEY LAND ON) IS THE LAST ONE IN THE STRING

blocks:
  - "WOOL:0"
  - "BOOKSHELF:5"
  - "COAL_BLOCK:10"
  - "BEACON:25"
  - "EMERALD_BLOCK:50"
  - "QUARTZ_BLOCK:100"
  - "SPONGE:200"
  - "HAY_BLOCK:300"
  - "MELON:400"
  - "TNT:500"
  - "DRAGON_EGG:1000"

start-location:
  world: "world"
  coords: "255,84,208"